# Generated by Django 6.0.7 on 2026-07-19 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_active_alter_service_name_and_more'),
        ('vehicles', '0004_vehicletype_alter_vehicleentry_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço base'),
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='services.service')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='vehicles.vehicletype', verbose_name='Tipo de Veículo')),
            ],
            options={
                'ordering': ['service__name', 'vehicle_type__name'],
                'constraints': [models.UniqueConstraint(fields=('service', 'vehicle_type'), name='unique_service_vehicle_price')],
            },
        ),
    ]
