# Generated by Django 6.0.7 on 2026-08-01 18:57

from django.db import migrations


def migrate_roles_to_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    User = apps.get_model('accounts', 'User')

    groups = {name: Group.objects.get_or_create(name=name)[0] for name in ('seguranca', 'tesoureira', 'admin')}

    for user in User.objects.exclude(role=''):
        group = groups.get(user.role)
        if group:
            user.groups.add(group)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(migrate_roles_to_groups, noop),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
