# Generated by Django 6.0.7 on 2026-08-01 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_role_groups_v2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_admin_dashboard', 'Pode ver o dashboard administrativo')]},
        ),
    ]
