# Generated by Django 6.0.7 on 2026-07-19 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashbox', '0002_payment_alt_identifier_payment_brand_payment_model_and_more'),
        ('vehicles', '0003_vehicleentry_alt_identifier_vehicleentry_no_plate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('ok', 'Conferem'), ('service_mismatch', 'Divergência de serviço'), ('value_mismatch', 'Divergência de valor'), ('no_payment', 'Sem pagamento'), ('no_entry', 'Sem registo de entrada'), ('unverifiable', 'Não verificável')], max_length=20)),
                ('expected_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('received_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('value_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('investigation_status', models.CharField(choices=[('pendente', 'Pendente'), ('resolvido', 'Resolvido'), ('justificado', 'Justificado'), ('fraude', 'Fraude confirmada')], default='pendente', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations', to='cashbox.payment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations', to='vehicles.vehicleentry')),
            ],
            options={
                'ordering': ['-date', 'status'],
            },
        ),
    ]
