# Generated by Django 6.0.7 on 2026-07-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleentry',
            name='plate',
            field=models.CharField(blank=True, max_length=20, verbose_name='Matrícula'),
        ),
    ]
