# Generated by Django 6.0.7 on 2026-07-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicleentry_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleentry',
            name='alt_identifier',
            field=models.CharField(blank=True, max_length=100, verbose_name='Chassis / Descrição'),
        ),
        migrations.AddField(
            model_name='vehicleentry',
            name='no_plate',
            field=models.BooleanField(default=False, verbose_name='Sem matrícula'),
        ),
    ]
