# Generated by Django 6.0.7 on 2026-07-19 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_and_migrate_legacy_models(apps, schema_editor):
    VehicleType = apps.get_model('vehicles', 'VehicleType')
    VehicleEntry = apps.get_model('vehicles', 'VehicleEntry')

    base_types = ['Carro', 'Mota', 'Carrinha', 'Jipe / SUV', 'Camião', 'Autocarro', 'Mini-bus']
    for name in base_types:
        VehicleType.objects.get_or_create(name=name, defaults={'is_approved': True})

    legacy_values = VehicleEntry.objects.values_list('model', flat=True).distinct()
    for value in legacy_values:
        name = value or 'Não especificado'
        vt, _ = VehicleType.objects.get_or_create(name=name, defaults={'is_approved': True})
        VehicleEntry.objects.filter(model=value).update(model=str(vt.pk))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicleentry_alt_identifier_vehicleentry_no_plate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tipo de veículo')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Aprovado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_types_added', to=settings.AUTH_USER_MODEL, verbose_name='Adicionado por')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_and_migrate_legacy_models, noop),
        migrations.AlterField(
            model_name='vehicleentry',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_entries', to='vehicles.vehicletype', verbose_name='Tipo de Veículo'),
        ),
    ]
