# Generated by Django 6.0.7 on 2026-07-20 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicletype_alter_vehicleentry_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleentry',
            name='alt_identifier',
        ),
    ]
