# Generated by Django 6.0.7 on 2026-07-20 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def revert_adopted_to_pendente(apps, schema_editor):
    VehicleEntry = apps.get_model('vehicles', 'VehicleEntry')
    VehicleEntry.objects.filter(status='adotado').update(status='pendente')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_remove_vehicleentry_alt_identifier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleentry',
            old_name='claimed_at',
            new_name='completed_at',
        ),
        migrations.RemoveField(
            model_name='vehicleentry',
            name='claimed_by',
        ),
        migrations.AddField(
            model_name='vehicleentry',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_entries_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(revert_adopted_to_pendente, noop),
        migrations.AlterField(
            model_name='vehicleentry',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('concluido', 'Concluído')], default='pendente', max_length=20),
        ),
    ]
