# Generated by Django 6.0.7 on 2026-08-01 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_rename_claimed_at_vehicleentry_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleentry',
            options={'ordering': ['-created_at'], 'permissions': [('manage_trash', 'Pode gerir o lixo de veículos (ver, restaurar, apagar definitivo)')], 'verbose_name_plural': 'Vehicle entries'},
        ),
    ]
