# Generated by Django 6.0.7 on 2026-07-19 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0001_initial'),
        ('services', '0002_alter_service_active_alter_service_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='alt_identifier',
            field=models.CharField(blank=True, max_length=100, verbose_name='Chassis / Descrição'),
        ),
        migrations.AddField(
            model_name='payment',
            name='brand',
            field=models.CharField(default='', max_length=50, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='payment',
            name='model',
            field=models.CharField(default='', max_length=50, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='payment',
            name='no_plate',
            field=models.BooleanField(default=False, verbose_name='Sem matrícula'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('mpesa_emola', 'M-Pesa / e-Mola')], default='dinheiro', max_length=20, verbose_name='Forma de pagamento'),
        ),
        migrations.AddField(
            model_name='payment',
            name='plate',
            field=models.CharField(blank=True, max_length=20, verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='payment',
            name='price_charged',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor cobrado'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor recebido'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.service', verbose_name='Serviço'),
        ),
    ]
