# Generated by Django 6.0.7 on 2026-07-19 22:47

import django.db.models.deletion
from django.db import migrations, models


def migrate_legacy_models(apps, schema_editor):
    VehicleType = apps.get_model('vehicles', 'VehicleType')
    Payment = apps.get_model('cashbox', 'Payment')

    legacy_values = Payment.objects.values_list('model', flat=True).distinct()
    for value in legacy_values:
        name = value or 'Não especificado'
        vt, _ = VehicleType.objects.get_or_create(name=name, defaults={'is_approved': True})
        Payment.objects.filter(model=value).update(model=str(vt.pk))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0002_payment_alt_identifier_payment_brand_payment_model_and_more'),
        ('vehicles', '0004_vehicletype_alter_vehicleentry_model'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_models, noop),
        migrations.AlterField(
            model_name='payment',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_new', to='vehicles.vehicletype', verbose_name='Tipo de Veículo'),
        ),
    ]
