# Generated by Django 6.0.7 on 2026-07-20 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0003_alter_payment_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='alt_identifier',
        ),
    ]
