# Generated by Django 6.0.7 on 2026-08-01 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0004_remove_payment_alt_identifier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashclosure',
            options={'ordering': ['-date_end'], 'permissions': [('close_period', 'Pode fechar período semanal/mensal')]},
        ),
    ]
